#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : mvn-azure-keyvault-java
Version  : 1.0.0
Release  : 1
URL      : https://github.com/Azure/azure-keyvault-java/archive/v1.0.0.tar.gz
Source0  : https://github.com/Azure/azure-keyvault-java/archive/v1.0.0.tar.gz
Source1  : https://repo1.maven.org/maven2/com/microsoft/azure/azure-keyvault-core/1.0.0/azure-keyvault-core-1.0.0.jar
Source2  : https://repo1.maven.org/maven2/com/microsoft/azure/azure-keyvault-core/1.0.0/azure-keyvault-core-1.0.0.pom
Summary  : No detailed summary available
Group    : Development/Tools
License  : MIT
Requires: mvn-azure-keyvault-java-data = %{version}-%{release}

%description
# Contributing
This project has adopted the [Microsoft Open Source Code of Conduct](https://opensource.microsoft.com/codeofconduct/). For more information see the [Code of Conduct FAQ](https://opensource.microsoft.com/codeofconduct/faq/) or contact [opencode@microsoft.com](mailto:opencode@microsoft.com) with any additional questions or comments.

%package data
Summary: data components for the mvn-azure-keyvault-java package.
Group: Data

%description data
data components for the mvn-azure-keyvault-java package.


%prep

%build

%install
mkdir -p %{buildroot}/usr/share/java/.m2/repository/com/microsoft/azure/azure-keyvault-core/1.0.0
cp %{SOURCE1} %{buildroot}/usr/share/java/.m2/repository/com/microsoft/azure/azure-keyvault-core/1.0.0/azure-keyvault-core-1.0.0.jar

mkdir -p %{buildroot}/usr/share/java/.m2/repository/com/microsoft/azure/azure-keyvault-core/1.0.0
cp %{SOURCE2} %{buildroot}/usr/share/java/.m2/repository/com/microsoft/azure/azure-keyvault-core/1.0.0/azure-keyvault-core-1.0.0.pom


%files
%defattr(-,root,root,-)

%files data
%defattr(-,root,root,-)
/usr/share/java/.m2/repository/com/microsoft/azure/azure-keyvault-core/1.0.0/azure-keyvault-core-1.0.0.jar
/usr/share/java/.m2/repository/com/microsoft/azure/azure-keyvault-core/1.0.0/azure-keyvault-core-1.0.0.pom
